artifact_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182
creation_time: 1741954718344
experiment_id: '475178814792087182'
last_update_time: 1741954718344
lifecycle_stage: active
name: Churn_Prediction_Experiments
