aliases: []
creation_timestamp: 1741975091463
current_stage: None
description: null
last_updated_timestamp: 1741975091463
name: Churn_LRModel
run_id: 39eaebf16f13495db1b600106f6d92b2
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/39eaebf16f13495db1b600106f6d92b2/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/39eaebf16f13495db1b600106f6d92b2/artifacts/logistic_regression_model
user_id: null
version: 9
