aliases: []
creation_timestamp: 1741955069911
current_stage: None
description: null
last_updated_timestamp: 1741955069911
name: Churn_RFModel
run_id: 16eab5fc9f7c4f2d9e33b45cd4228cd2
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/16eab5fc9f7c4f2d9e33b45cd4228cd2/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/16eab5fc9f7c4f2d9e33b45cd4228cd2/artifacts/random_forest_model
user_id: null
version: 2
