aliases: []
creation_timestamp: 1741955605333
current_stage: None
description: null
last_updated_timestamp: 1741955605333
name: Churn_LRModel
run_id: e74dfdb2b9a346dbbff5f83713c828c0
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/e74dfdb2b9a346dbbff5f83713c828c0/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/e74dfdb2b9a346dbbff5f83713c828c0/artifacts/logistic_regression_model
user_id: null
version: 4
