artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/ceca20c4a36b4d98b35c72e7c0a0102c/artifacts
end_time: 1741955984736
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: ceca20c4a36b4d98b35c72e7c0a0102c
run_name: RandomForest
run_uuid: ceca20c4a36b4d98b35c72e7c0a0102c
source_name: ''
source_type: 4
source_version: ''
start_time: 1741955981460
status: 3
tags: []
user_id: lizapersonal
