aliases: []
creation_timestamp: 1741960347772
current_stage: None
description: null
last_updated_timestamp: 1741960347772
name: Churn_RFModel
run_id: 2a283bbcced247e49699ae2735dd991f
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/2a283bbcced247e49699ae2735dd991f/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/2a283bbcced247e49699ae2735dd991f/artifacts/random_forest_model
user_id: null
version: 7
