aliases: []
creation_timestamp: 1741955696493
current_stage: None
description: null
last_updated_timestamp: 1741955696493
name: Churn_LRModel
run_id: feb185ee42c94cb987485a3e8f4a460c
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/feb185ee42c94cb987485a3e8f4a460c/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/feb185ee42c94cb987485a3e8f4a460c/artifacts/logistic_regression_model
user_id: null
version: 5
