artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/2a283bbcced247e49699ae2735dd991f/artifacts
end_time: 1741960347782
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: 2a283bbcced247e49699ae2735dd991f
run_name: RandomForest
run_uuid: 2a283bbcced247e49699ae2735dd991f
source_name: ''
source_type: 4
source_version: ''
start_time: 1741960344016
status: 3
tags: []
user_id: lizapersonal
