artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/a5d5fb780e404bcab9aa8643b44b8297/artifacts
end_time: 1741970534096
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: a5d5fb780e404bcab9aa8643b44b8297
run_name: RandomForest
run_uuid: a5d5fb780e404bcab9aa8643b44b8297
source_name: ''
source_type: 4
source_version: ''
start_time: 1741970530797
status: 3
tags: []
user_id: lizapersonal
