aliases: []
creation_timestamp: 1741955984730
current_stage: None
description: null
last_updated_timestamp: 1741955984730
name: Churn_RFModel
run_id: ceca20c4a36b4d98b35c72e7c0a0102c
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/ceca20c4a36b4d98b35c72e7c0a0102c/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/ceca20c4a36b4d98b35c72e7c0a0102c/artifacts/random_forest_model
user_id: null
version: 6
