artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7e3f104a8e364d13958abcec734d8e9a/artifacts
end_time: 1741955608553
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: 7e3f104a8e364d13958abcec734d8e9a
run_name: RandomForest
run_uuid: 7e3f104a8e364d13958abcec734d8e9a
source_name: ''
source_type: 4
source_version: ''
start_time: 1741955605338
status: 3
tags: []
user_id: lizapersonal
