aliases: []
creation_timestamp: 1741955419234
current_stage: None
description: null
last_updated_timestamp: 1741955419234
name: Churn_RFModel
run_id: 7660c4ae021c472d9c255ca4306d3db9
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7660c4ae021c472d9c255ca4306d3db9/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7660c4ae021c472d9c255ca4306d3db9/artifacts/random_forest_model
user_id: null
version: 3
