artifact_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/0
creation_time: 1741954718339
experiment_id: '0'
last_update_time: 1741954718339
lifecycle_stage: active
name: Default
