aliases: []
creation_timestamp: 1741970530787
current_stage: None
description: null
last_updated_timestamp: 1741970530787
name: Churn_LRModel
run_id: fc3c0ba02063495a948198674d04a9bd
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/fc3c0ba02063495a948198674d04a9bd/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/fc3c0ba02063495a948198674d04a9bd/artifacts/logistic_regression_model
user_id: null
version: 8
