aliases: []
creation_timestamp: 1741976359471
current_stage: None
description: null
last_updated_timestamp: 1741976359471
name: Churn_LRModel
run_id: c5af289df0e8482698d6749881ba16f4
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/c5af289df0e8482698d6749881ba16f4/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/c5af289df0e8482698d6749881ba16f4/artifacts/logistic_regression_model
user_id: null
version: 10
