artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/16eab5fc9f7c4f2d9e33b45cd4228cd2/artifacts
end_time: 1741955069914
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: 16eab5fc9f7c4f2d9e33b45cd4228cd2
run_name: RandomForest
run_uuid: 16eab5fc9f7c4f2d9e33b45cd4228cd2
source_name: ''
source_type: 4
source_version: ''
start_time: 1741955066678
status: 3
tags: []
user_id: lizapersonal
