aliases: []
creation_timestamp: 1741955608549
current_stage: None
description: null
last_updated_timestamp: 1741955608549
name: Churn_RFModel
run_id: 7e3f104a8e364d13958abcec734d8e9a
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7e3f104a8e364d13958abcec734d8e9a/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7e3f104a8e364d13958abcec734d8e9a/artifacts/random_forest_model
user_id: null
version: 4
