aliases: []
creation_timestamp: 1741976362631
current_stage: None
description: null
last_updated_timestamp: 1741976362631
name: Churn_RFModel
run_id: 0c06d688ad184090a43f03dcfc49233b
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/0c06d688ad184090a43f03dcfc49233b/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/0c06d688ad184090a43f03dcfc49233b/artifacts/random_forest_model
user_id: null
version: 10
