aliases: []
creation_timestamp: 1741955066674
current_stage: None
description: null
last_updated_timestamp: 1741955066674
name: Churn_LRModel
run_id: 31e2be75892d4486809277f67e94853c
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/31e2be75892d4486809277f67e94853c/artifacts/logistic_regression_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/31e2be75892d4486809277f67e94853c/artifacts/logistic_regression_model
user_id: null
version: 2
