aliases: []
creation_timestamp: 1741955700550
current_stage: None
description: null
last_updated_timestamp: 1741955700550
name: Churn_RFModel
run_id: 72eff5f3852049e899286f87035dab86
run_link: null
source: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/72eff5f3852049e899286f87035dab86/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/72eff5f3852049e899286f87035dab86/artifacts/random_forest_model
user_id: null
version: 5
