artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/feb185ee42c94cb987485a3e8f4a460c/artifacts
end_time: 1741955696498
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: feb185ee42c94cb987485a3e8f4a460c
run_name: LogisticRegression
run_uuid: feb185ee42c94cb987485a3e8f4a460c
source_name: ''
source_type: 4
source_version: ''
start_time: 1741955690629
status: 3
tags: []
user_id: lizapersonal
