artifact_uri: file:///Users/lizapersonal/PycharmProjects/data-management-pipeline/mlflow_runs/475178814792087182/7b0716ba68e944b299a3faef4b29bf88/artifacts
end_time: 1741955416316
entry_point_name: ''
experiment_id: '475178814792087182'
lifecycle_stage: active
run_id: 7b0716ba68e944b299a3faef4b29bf88
run_name: LogisticRegression
run_uuid: 7b0716ba68e944b299a3faef4b29bf88
source_name: ''
source_type: 4
source_version: ''
start_time: 1741955410693
status: 3
tags: []
user_id: lizapersonal
